{% set version = "7.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-eulerr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/eulerr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/eulerr/eulerr_{{ version }}.tar.gz
  sha256: 4e0dce2b240a97e2bfe22b3848c7ff9e1fc684ed3b007c94adb97a8bc6a0842b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-gensa
    - r-rcpp
    - r-rcpparmadillo >=0.7.600.1.0
    - r-polyclip
    - r-polylabelr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-gensa
    - r-rcpp
    - r-rcpparmadillo >=0.7.600.1.0
    - r-polyclip
    - r-polylabelr

test:
  commands:
    - $R -e "library('eulerr')"           # [not win]
    - "\"%R%\" -e \"library('eulerr')\""  # [win]

about:
  home: https://github.com/jolars/eulerr, https://jolars.github.io/eulerr/
  license: GPL-3.0-only
  summary: Generate area-proportional Euler diagrams using numerical optimization. An Euler diagram is a generalization of a Venn diagram, relaxing the criterion that all interactions need to be represented. Diagrams may be fit with ellipses and circles via a wide range of inputs and can be visualized in numerous ways.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - mxr-conda
    - bubblyorca

# Package: eulerr
# Title: Area-Proportional Euler and Venn Diagrams with Ellipses
# Version: 6.0.0
# Authors@R: c(person("Johan", "Larsson", email = "mail@larssonjohan.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4029-5945")), person("A. Jonathan R.", "Godfrey", role = "ctb"), person("Peter", "Gustafsson", role = "ctb"), person("David H.", "Eberly", role = "ctb", comment = "geometric algorithms"), person("Emanuel", "Huber", role = "ctb", comment = "root solver code"), person("Kamil", "Slowikowski", role = c("ctb", "cph"), comment = "modified code from ggrepel"))
# Description: Generate area-proportional Euler diagrams using numerical optimization. An Euler diagram is a generalization of a Venn diagram, relaxing the criterion that all interactions need to be represented. Diagrams may be fit with ellipses and circles via a wide range of inputs and can be visualized in numerous ways.
# Depends: R (>= 3.3.0)
# Imports: GenSA, graphics, grDevices, grid, polyclip, polylabelr, Rcpp, stats, utils
# Suggests: covr, knitr, lattice, pBrackets, RConics, rmarkdown, testthat, spelling
# LinkingTo: Rcpp (>= 0.12.12), RcppArmadillo (>= 0.7.600.1.0)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# VignetteBuilder: knitr
# URL: https://github.com/jolars/eulerr, https://jolars.github.io/eulerr/
# BugReports: https://github.com/jolars/eulerr/issues
# RoxygenNote: 6.1.1
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2019-09-27 20:50:17 UTC; johan
# Author: Johan Larsson [aut, cre] (<https://orcid.org/0000-0002-4029-5945>), A. Jonathan R. Godfrey [ctb], Peter Gustafsson [ctb], David H. Eberly [ctb] (geometric algorithms), Emanuel Huber [ctb] (root solver code), Kamil Slowikowski [ctb, cph] (modified code from ggrepel)
# Maintainer: Johan Larsson <mail@larssonjohan.com>
# Repository: CRAN
# Date/Publication: 2019-09-27 21:10:02 UTC
